import Head from 'next/head'
import { useEffect, useState } from 'react'
import { getNotes } from '../services/noteService';
import styles from '../styles/Home.module.css'

interface Note {
  _id: string;
  text: string;
  timestamp: number;
}

export default function Home() {
  const [notes, setNotes] = useState<Note[]>([]);

  useEffect(() => {
    (async () => {
      const notes = await getNotes();
      setNotes(notes);
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Notes notes={notes}/>
      </main>
    </div>
  )
}

function Note({note}: {note: Note}) {
  return (
    <div>
      <h3>{note.timestamp}</h3>
      <div>{note.text}</div>
    </div>
  )
}

function Notes({notes}: {notes: Note[]}) {
  return (
    <div>
      {notes.map(note => {
        return <Note note={note} />
      })}
    </div>
  )
}
